export const config = {
  scene_bg_color: 0x000000,
  earthUV: "src/assets/earthUV2.jpg",
  earthRotationSpeed: 0.0025,
  earthRadius: 4,
  cameraZPosition: 10,
  starColor: 0xffffff,
  startCount: 2000,
  showEarth: true,
  showAtmosphere: true,
  showAxes: true,
  Earth: "Earth",
  Atmosphere: "Atmosphere",
  Axes: "Axes",
  pointHeight: 0.4,
  pointColor: "#3BF7FF",
  pointsOpacity: 0.8,
  atmosphereScale: 1,
};
